services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5
      start_period: 5s
  app:
    image: mrpatterson/nest-pnpm-docker
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
volumes:
  postgres-db-volume:
